export const posts = [
  {
    id: 1,
    category: "Essay",
    title: "The Quiet Art of Paying Attention",
    excerpt: "In an age of relentless stimulation, the practice of genuine observation has become a radical act — one that transforms the mundane into the extraordinary.",
    author: "Eleanor Voss",
    date: "May 22, 2026",
    readTime: "8 min read",
    featured: true,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80",
  },
  {
    id: 2,
    category: "Culture",
    title: "What Libraries Tell Us About Civilisation",
    excerpt: "Every great library is a statement of belief — that knowledge matters, that it should be preserved, and that access to it is a common right.",
    author: "James Hartwell",
    date: "May 15, 2026",
    readTime: "6 min read",
    featured: false,
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80",
  },
  {
    id: 3,
    category: "Philosophy",
    title: "On Slowness as a Form of Resistance",
    excerpt: "To move deliberately in a world that prizes speed above all else is not laziness. It is, perhaps, the most subversive thing a person can do.",
    author: "Mira Delacroix",
    date: "May 8, 2026",
    readTime: "5 min read",
    featured: false,
    image: "https://images.unsplash.com/photo-1474540412665-1cdae210ae6b?w=800&q=80",
  },
  {
    id: 4,
    category: "Travel",
    title: "A Week in Lisbon, Without a Plan",
    excerpt: "The best discoveries in any city come not from guidebooks but from the willingness to be lost — and the courage to remain so.",
    author: "Thomas Adeyemi",
    date: "April 30, 2026",
    readTime: "7 min read",
    featured: false,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
  },
  {
    id: 5,
    category: "Literature",
    title: "Why We Still Need the Short Story",
    excerpt: "The short story is not a lesser form of the novel. It is its own country — with its own laws, its own weather, its own magnificent silences.",
    author: "Eleanor Voss",
    date: "April 22, 2026",
    readTime: "9 min read",
    featured: false,
    image: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=800&q=80",
  },
  {
    id: 6,
    category: "Science",
    title: "The Language of Fungi",
    excerpt: "Beneath every forest floor lies a vast, silent network of communication older than language itself. We are only beginning to learn how to listen.",
    author: "Sasha Nguyen",
    date: "April 14, 2026",
    readTime: "10 min read",
    featured: false,
    image: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=800&q=80",
  },
];

export const categories = ["All", "Essay", "Culture", "Philosophy", "Travel", "Literature", "Science"];
